# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
     
    - name: Github Sync
      uses: repo-sync/github-sync@v2.3.0          
      with:
        source_repo: "https://github.com/Wind4/vlmcsd.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.GITHUB_TOKEN }}
